GET http://localhost:3000/cursos HTTP/1.1

###

POST http://localhost:3000/cursos HTTP/1.1
content-type: application/json
{
    "nome": "PHP OO",
    "valor":50.00
}

###

PUT http://localhost:3000/cursos/3 HTTP/1.1
content-type: application/json

{
    "nome": "PHP OO",
    "valor": "78.00"
}